#!/bin/bash

#
# var for usage / debug
#

RUNNING_INFO="
    download path :          $DL_PATH
    download config file :   $DL_CONF_PATH
    youtube-dl config file : $YT_CONF_PATH

    log path :               $LOG_PATH
    lock directory path :    $LOCK_DIR

    dl mode :                $DL_MODE (0=all,1=youtube,2=soundcloud,3=disable_dl)
    output mode :            $OUTPUT_MODE (0=logfile,1=std)
    loglevel :               $LEVEL (0=error,1=info,2=warn,3=debug)

    new target :             $NEW_TARGET
    show url :               $SHOW
    comment entry :          $TO_COMMENT
"

USAGE="
Usage : dl -d [path] -c [path] -y [path] -m [0..3] -s -a [Entry URL] -r [Entry] -l [0..3] -o [1..2] -i -h

Run dl, a simple music downloader script.

Download configuration options :

    -d:     Directory root path for downloads. A full or relative path can be provide.
            Default : [$DL_PATH]
    -c:     Configuration file for the download. A full path must be provide.
            Default : [$DL_CONF_PATH]
    -y:     Youtube-dl configuration file path. A full path must be provide.
            Default : [$YT_CONF_PATH]
    -m:     Mode (0=all,1=youtube,2=soundcloud,3=disable_dl)
            Default : [$DL_MODE]

Configuration options :

    -s:     Show the entry in the config file
    -a:     Append entry to the config file.
            Argument must be in format [EntryDirectory EntryURL]
    -r:     Comment/Uncomment a entry from the config file.
            Argument must be in format [EntryDirectory]

Misc options :
    -l:     log level (0=error,1=info,2=warn,3=debug).
            Default : [$LEVEL]
    -o:     Output mode. (0=logfile,1=std)
    -i:     install required packages
    -h:     display this screen
"

#
# var setted by the cli // default value
#

DL_MODE=0
YT_CONF_PATH=
INSTALL=0
OUTPUT_MODE=0
SHOW=0
NEW_TARGET=
ENTRY=

#
# Misc
#

# install scdl if needed
install_scdl() {
    exit_if_not_installed "pip3"
    pip3 install scdl
    info "scdl (a soundcloud downloader) installed"
}

# install youtube-dl
install_yt() {
    exit_if_not_installed "curl"
    sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
    sudo chmod a+rx /usr/local/bin/youtube-dl
    info "youtube-dl (a youtube dowmloader) installed"
}

#
# Soundcloud functions
#

# define if the url has to be dl via scdl
is_soundcloud() {
    local url=$1
    if [ `echo $url | grep "soundcloud"` ] &&
           ( [ $DL_MODE -eq 0 ] || [ $DL_MODE -eq 2 ] ); then
        echo 1
    else
        echo 0
    fi
}

# download playlists from soundcloud
download_from_sc_playlist() {
    local url=$1
    scdl -l "$url" -p -c --hide-progress --download-archive .scdl_playlist.txt
    echo $?
}

# download likes from soundcloud
download_from_sc_like() {
    local url=$1
    scdl -l "$url" -f -c --hide-progress --download-archive .scdl_like.txt
    echo $?
}

#
# YouTube function
#

# download (playlist/track) from youtube
download_from_yt() {
    local url=$1
    # add version at the beginning of the log file ?
    youtube-dl --verbose --config-location $YT_CONF_PATH $url
    echo $?
}

# define if the url has to be dl via youtube-dl
is_youtube() {
    local url=$1
    if [ `echo $url | grep "youtube"` ] &&
           ( [ $DL_MODE -eq 0 ] || [ $DL_MODE -eq 1 ] ); then
        echo 1
    else
        echo 0
    fi
}
