#!/bin/bash

# run id3v2 to write id3 v1 tags

set_title() {
    local trackPath=$1
    local title=$2

    id3v2 -1 -t "$title" "$trackPath"
}

set_artist() {
    local trackPath=$1
    local artist=$2

    id3v2 -1 -a "$artist" "$trackPath"
}

set_date() {
    local trackPath=$1
    local date=$2

    id3v2 -1 -y "$date" "$trackPath"
}

set_cover() {
    local trackPath=$1
    local covert=$2
}

set_cover() {
    local trackPath=$1
    local meta=$2
}