#!/bin/bash

LEVEL=2

function usage {
    (>&2 echo -e "$1")
}

function error {
    (>&2 echo -e "\e[101m$1\e[0m")
}

function debug {
    if [ $LEVEL -gt 2 ]; then
        echo -e "\e[93m$1\e[0m"
    fi
}

function warn {
    if [ $LEVEL -gt 1 ]; then
        echo -e "\e[1mBold$1\e[0m"
    fi
}

function info {
    if [ $LEVEL -gt 0 ]; then
        echo -e "\e[92m$1\e[0m"
    fi
}

exit_if_not_installed() {
    local toTest=$1

    #    info "Testing $toTest"
    if [ `which $toTest` == "" ]; then
        error "Can't find the $toTest package"
        error "Please install the $toTest package before running"
        exit 2
    fi

    #    debug "$toTest is present on this system"
}

create_dir_if_not() {
    local path=$1

    if [ ! -d "$path" ]; then
        mkdir -p $path
    fi
}

check_if_dir_exist() {
    local dir=$1
    local what=$2

    if [ ! -d "$dir" ]; then
        error "Invalid dir path for $what : [$dir]"
        exit 3
    fi
}

check_if_file_exist() {
    local file=$1
    local what=$2

    if [ ! -f "$file" ]; then
        error "Invalid file path for the $wath : [$file]"
        exit 3
    fi
}
